const menu = [
  "Green",
  "Magenta",
  "Red",
  "Blue",
  "Orange",
  "Purple",
  "Yellow",
  "Tan",
  "Beige",
  "Turquoise",
  "Dark green",
  "Dark brown",
  "A dull blue-gray",
  "Plaid",
  "Orange with green spots",
  "Pink",
  "Green glow in the dark",
  "Rainbow (all the colors in up and down stripes)",
  "Tartan",
  "Green with black and purple stripes",
  "Silver",
  "Gold",
  "Animal print",
  "Invisible",
];

module.exports = menu;
